### ISSUE TITLE
Use "Pageable pageable" as parameter instead of mentioning the parameters explicitly 

### ISSUE THREAD

**Issue by jamilxt** [meheedihasaan/quiz-portal#38]
https://github.com/meheedihasaan/quiz-portal/blob/00c6a58e7f7e1ca4385e64f815640e6e6cb1a6e9/src/main/java/com/quiz/portal/service/impl/CategoryServiceImpl.java#L29

Ref: https://www.baeldung.com/spring-data-jpa-pagination-sorting

**Comment by meheedihasaan** [comment]
If I pass Pageable pageable as parameter, then I have to write Sort type and Pageable pageable = PageRequest.of(pageNumber, pageSize, sort) in Controller class. Right?

**Comment by jamilxt** [comment]
Yeah, pass it to service layer from controller.

**Comment by meheedihasaan** [comment]
Thank you 😍
