### ISSUE TITLE
Constant Class should be immutable

### ISSUE THREAD

**Issue by jamilxt** [meheedihasaan/quiz-portal#40]
https://github.com/meheedihasaan/quiz-portal/blob/00c6a58e7f7e1ca4385e64f815640e6e6cb1a6e9/src/main/java/com/quiz/portal/constsant/AppConstant.java#L3

Read this article to learn: https://www.baeldung.com/java-constants-good-practices#2-constants-class

**Comment by meheedihasaan** [comment]
Sorry. It's a big a mistake. As the constant properties remain unchanged, the class which contains constant properties should not be inherited. So it should be marked as final. I will fix this as soon as possible.

**Comment by jamilxt** [comment]
Read the article fully before come to a conclusion.
